---
- name: Verify
  hosts: all
  tasks:
    - name: Install netstat
      when: ansible_os_family == 'RedHat'
      ansible.builtin.yum:
        name:
          - net-tools
          - procps
        state: present

    - name: Install netstat
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name:
          - net-tools
          - procps
        state: present
        update_cache: true

    - name: Execute vector
      ansible.builtin.command: vector --version
      changed_when: false
      register: vector_version_rc

    - name: Check port 6000 is open
      community.general.listen_ports_facts:

    - name: Assert vector is installed
      ansible.builtin.assert:
        that:
          - vector_version_rc is success
          - 6000 in open_ports
      vars:
        open_ports: "{{ ansible_facts.tcp_listen | map(attribute='port') }}"
